<a href="https://colab.research.google.com/github/BlackCurrantDS/ATiML-Project/blob/master/Features_Union.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook imports the metadat features, emotions, sentimen analysis output files and merges then on ID as comibed feature set

In [ ]:
import pandas as pd

#Getting data into dataframe from all features
df_meta_train = pd.read_csv("df_meta_train.csv", index_col=0)
df_meta_train.shape

(155, 27)

In [ ]:
vader_sentiment_train = pd.read_csv("vader_sentiment_train.csv", index_col=0)
vader_sentiment_train.shape

(155, 6)

In [ ]:
emotions_analysis_train = pd.read_csv("emotions_amalysis_train.csv", index_col=0)
emotions_analysis_train.shape

(155, 12)

In [ ]:
emotions_analysis_train.head(1)

    ID       genre  positive  ...       joy  surprise     trust
0  214  Allegories  0.082397  ...  0.047112  0.050337  0.062359

[1 rows x 12 columns]

In [ ]:
"""#Getting data from  training books
books_train = pd.read_csv("books_test.csv", index_col=0)
books_train = books_train[['FileNo', 'Author_Name', 'Book_Name']]"""

'#Getting data from  training books\nbooks_train = pd.read_csv("books_test.csv", index_col=0)\nbooks_train = books_train[[\'FileNo\', \'Author_Name\', \'Book_Name\']]'

In [ ]:
data_frames = [df_meta_train,vader_sentiment_train,emotions_analysis_train] #, books_train

In [ ]:
#merging all the features
from functools import reduce

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['ID']), data_frames).fillna('void')

In [ ]:
df_merged.head(1)

   index   ID     genre_x  ...       joy  surprise     trust
0    114  214  Allegories  ...  0.047112  0.050337  0.062359

[1 rows x 43 columns]

In [ ]:
df_merged.shape

(155, 43)

In [ ]:
df_merged.drop(['genre_x', 'genre_y' ], axis = 1)

     index   ID  book_lenght  ...       joy  surprise     trust
0      114  214       337103  ...  0.047112  0.050337  0.062359
1      315  387        50959  ...  0.034370  0.039280  0.073650
2      100  200       140074  ...  0.051125  0.038405  0.066292
3      211  311       584889  ...  0.047258  0.045664  0.061208
4      151  251       126433  ...  0.045351  0.039197  0.057013
..     ...  ...          ...  ...       ...       ...       ...
150     17  117       883130  ...  0.028464  0.046700  0.048227
151     15  115       324144  ...  0.025412  0.042078  0.049794
152    112  212       140074  ...  0.051125  0.038405  0.066292
153    220  320       358038  ...  0.042117  0.044177  0.059211
154    764  405       540262  ...  0.042776  0.048296  0.070788

[155 rows x 41 columns]

In [ ]:
df_merged.to_csv("features_train.csv")
#df_merged.to_csv("features_validation.csv")
#df_merged.to_csv("features_test.csv")