<a href="https://colab.research.google.com/github/BlackCurrantDS/ATiML-Project/blob/master/Scaling_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
features_train = pd.read_csv("features_validation.csv", index_col=0)

In [53]:
features_train.head(1)

   FileNo  ...                                        Book_Name
0   34947  ...  The House of Strange Secrets: A Detective Story

[1 rows x 44 columns]

In [0]:
#features_validation = pd.read_csv("features_validation.csv", index_col=0)

In [0]:
#features_test = pd.read_csv("features_test.csv", index_col=0)

In [56]:
import numpy as np
print ('Shape of features_train Matrix: ', features_train.shape)
print ('Amount of Non-Zero occurences: ', np.count_nonzero(features_train.values))
print ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_train.values) /
                                 (features_train.shape[0] * features_train.shape[1])))

Shape of features_train Matrix:  (11, 44)
Amount of Non-Zero occurences:  451
sparsity: 93.18%

In [57]:
"""print ('Shape of features_validation Matrix: ', features_validation.shape)
print ('Amount of Non-Zero occurences: ', np.count_nonzero(features_validation.values))
print ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_validation.values) /
                                 (features_validation.shape[0] * features_validation.shape[1])))"""

"print ('Shape of features_validation Matrix: ', features_validation.shape)\nprint ('Amount of Non-Zero occurences: ', np.count_nonzero(features_validation.values))\nprint ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_validation.values) /\n                                 (features_validation.shape[0] * features_validation.shape[1])))"

In [58]:
"""print ('Shape of features_test Matrix: ', features_test.shape)
print ('Amount of Non-Zero occurences: ', np.count_nonzero(features_test.values))
print ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_test.values) /
                                 (features_test.shape[0] * features_test.shape[1])))"""

"print ('Shape of features_test Matrix: ', features_test.shape)\nprint ('Amount of Non-Zero occurences: ', np.count_nonzero(features_test.values))\nprint ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_test.values) /\n                                 (features_test.shape[0] * features_test.shape[1])))"

In [0]:
from sklearn.preprocessing import StandardScaler

data = features_train.copy() #copying data frame

In [0]:
del data['genre_x']
del data['genre_y']
del data['Author_Name']
del data['Book_Name']
del data['genre']

In [61]:
data.head()

   FileNo  book_lenght  book_sen  ...       joy  surprise     trust
0   34947       287704      2892  ...  0.021787  0.047136  0.058098
1   48297       242140      2178  ...  0.025787  0.037155  0.049355
2   27549       408602      4765  ...  0.031966  0.045992  0.063454
3   16968       284238      6177  ...  0.046112  0.052574  0.051369
4   37081       319954      3047  ...  0.030595  0.035311  0.061520

[5 rows x 39 columns]

In [0]:
normalizer = StandardScaler()
data_scaled = normalizer.fit_transform(data.iloc[:,data.columns!='FileNo'])
data_norm = pd.DataFrame(np.column_stack((data['FileNo'].values,data_scaled)),columns = data.columns).set_index(data.index)

In [63]:
data_norm.head()

    FileNo  book_lenght  book_sen  ...       joy  surprise     trust
0  34947.0    -0.326653 -0.632093  ... -1.290688  0.288580 -0.290886
1  48297.0    -0.629771 -1.074873  ... -0.953683 -1.454980 -1.309384
2  27549.0     0.477630  0.529431  ... -0.433102  0.088768  0.333077
3  16968.0    -0.349711  1.405070  ...  0.758729  1.238480 -1.074786
4  37081.0    -0.112107 -0.535971  ... -0.548543 -1.777145  0.107740

[5 rows x 39 columns]

In [64]:
data_norm.FileNo.astype(int) #changed data type of column

0     34947
1     48297
2     27549
3     16968
4     37081
5      7842
6     41314
7     10067
8     18443
9     41340
10    32560
Name: FileNo, dtype: int64

In [65]:
data_norm.head(1)

    FileNo  book_lenght  book_sen  ...       joy  surprise     trust
0  34947.0    -0.326653 -0.632093  ... -1.290688   0.28858 -0.290886

[1 rows x 39 columns]

In [0]:
#merging data frame
features_train_subset = features_train[['FileNo', 'genre', 'Author_Name', 'Book_Name']]
features_scaled_train = pd.merge(data_norm, features_train_subset , on='FileNo')

In [67]:
features_scaled_train.shape

(11, 42)

In [68]:
features_scaled_train.head(5)

    FileNo  ...                                          Book_Name
0  34947.0  ...    The House of Strange Secrets: A Detective Story
1  48297.0  ...            A Soldier's Daughter- and Other Stories
2  27549.0  ...                                  The Seven Secrets
3  16968.0  ...                               The Bad Man: A Novel
4  37081.0  ...  In Strange Company: A Story of Chili and the S...

[5 rows x 42 columns]

In [0]:
#features_scaled_train.to_csv("features_scaled_train.csv")
features_scaled_train.to_csv("features_scaled_validation.csv")
#features_scaled_train.to_csv("features_scaled_test.csv")