<a href="https://colab.research.google.com/github/BlackCurrantDS/ATiML-Project/blob/master/Scaling_Features_Std.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
features_train = pd.read_csv("features_test.csv", index_col=0)

In [ ]:
#features_train.head(1)

In [ ]:
#features_validation = pd.read_csv("features_validation.csv", index_col=0)

In [ ]:
#features_test = pd.read_csv("features_test.csv", index_col=0)

In [ ]:
import numpy as np
print ('Shape of features_train Matrix: ', features_train.shape)
print ('Amount of Non-Zero occurences: ', np.count_nonzero(features_train.values))
print ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_train.values) /
                                 (features_train.shape[0] * features_train.shape[1])))

Shape of features_train Matrix:  (12, 44)
Amount of Non-Zero occurences:  505
sparsity: 95.64%

In [ ]:
"""print ('Shape of features_validation Matrix: ', features_validation.shape)
print ('Amount of Non-Zero occurences: ', np.count_nonzero(features_validation.values))
print ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_validation.values) /
                                 (features_validation.shape[0] * features_validation.shape[1])))"""

"print ('Shape of features_validation Matrix: ', features_validation.shape)\nprint ('Amount of Non-Zero occurences: ', np.count_nonzero(features_validation.values))\nprint ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_validation.values) /\n                                 (features_validation.shape[0] * features_validation.shape[1])))"

In [ ]:
"""print ('Shape of features_test Matrix: ', features_test.shape)
print ('Amount of Non-Zero occurences: ', np.count_nonzero(features_test.values))
print ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_test.values) /
                                 (features_test.shape[0] * features_test.shape[1])))"""

"print ('Shape of features_test Matrix: ', features_test.shape)\nprint ('Amount of Non-Zero occurences: ', np.count_nonzero(features_test.values))\nprint ('sparsity: %.2f%%' % (100.0 * np.count_nonzero(features_test.values) /\n                                 (features_test.shape[0] * features_test.shape[1])))"

In [ ]:
from sklearn.preprocessing import StandardScaler

data = features_train.copy() #copying data frame

In [ ]:
del data['genre_x']
del data['genre_y']
del data['Author_Name']
del data['Book_Name']
del data['genre']

In [ ]:
data.head()

   FileNo  book_lenght  book_sen  ...       joy  surprise     trust
0   43716       540262      5512  ...  0.042776  0.048296  0.070788
1   30137       456130      5278  ...  0.051613  0.049303  0.058760
2  137212       582728      7059  ...  0.048281  0.034109  0.062105
3   35077       498452      5590  ...  0.057190  0.062324  0.064131
4   46064       361313      5114  ...  0.029071  0.035059  0.049256

[5 rows x 39 columns]

In [ ]:
normalizer = StandardScaler()
data_scaled = normalizer.fit_transform(data.iloc[:,data.columns!='FileNo'])
data_norm = pd.DataFrame(np.column_stack((data['FileNo'].values,data_scaled)),columns = data.columns).set_index(data.index)

In [ ]:
data_norm.head()

     FileNo  book_lenght  book_sen  ...       joy  surprise     trust
0   43716.0     1.078764  0.433424  ...  0.349361  0.088346  1.741793
1   30137.0     0.344949  0.265855  ...  1.036632  0.200627  0.480342
2  137212.0     1.449160  1.541243  ...  0.777442 -1.492627  0.831157
3   35077.0     0.714089  0.489281  ...  1.470365  1.651615  1.043677
4   46064.0    -0.482062  0.148413  ... -0.716533 -1.386776 -0.516343

[5 rows x 39 columns]

In [ ]:
data_norm.FileNo.astype(int) #changed data type of column

0      43716
1      30137
2     137212
3      35077
4      46064
5      30838
6      44819
7      37664
8       5151
9      40566
10     21067
11     26925
Name: FileNo, dtype: int64

In [ ]:
data_norm.head(1)

    FileNo  book_lenght  book_sen  ...       joy  surprise     trust
0  43716.0     1.078764  0.433424  ...  0.349361  0.088346  1.741793

[1 rows x 39 columns]

In [ ]:
#merging data frame
features_train_subset = features_train[['FileNo', 'genre', 'Author_Name', 'Book_Name']]
features_scaled_train = pd.merge(data_norm, features_train_subset , on='FileNo')

In [ ]:
features_scaled_train.shape

(12, 42)

In [ ]:
features_scaled_train.head(5)

     FileNo  book_lenght  ...         Author_Name                       Book_Name
0   43716.0     1.078764  ...     Aimard| Gustave                 The Adventurers
1   30137.0     0.344949  ...  Libbey| Laura Jean   Daisy Brooks- A Perilous Love
2  137212.0     1.449160  ...    Melville| Herman  Mardi: and A Voyage Thither ||
3   35077.0     0.714089  ...        Austin| Anne                      Girl Alone
4   46064.0    -0.482062  ...      Wells| Carolyn           The Deep Lake Mystery

[5 rows x 42 columns]

In [ ]:
#features_scaled_train.to_csv("features_scaled_train.csv")
#features_scaled_train.to_csv("features_scaled_validation.csv")
features_scaled_train.to_csv("features_scaled_test.csv")